---
- name: Preparing disks for LVM Playbook (SAS 9.4)
  connection: local
  hosts: 127.0.0.1
  tasks:
   
    - name: Include variables
      include_vars:
        name: disk_vars
        file: disk_vars.yml

    - name: Workaround for non-idempotent parted module
      shell: /usr/sbin/fdisk -l | /usr/bin/grep "{{ item.device }}1"
      register: disk_created

      with_items:
        - "{{ disk_vars.disks }}"

    - name: Prepare devices for LVM.
      parted:
        label: "{{ item.label }}"
        device: "/dev/{{ item.device }}"
        number: "{{ item.device_number }}"
        flags: [ lvm ]
        state: present
        part_start: 0%
        part_end: 100%
      when: not {{ item.device }}1 in disk_created.stdout

      with_items:
        - "{{ disk_vars.disks }}"

